### PR TITLE
Add Newsround colors

### PR DESCRIPTION
**Pull request by akabiru**
### What does this PR do?

Adds Newsround core colors to be used in [alephamp renderer](https://github.com/bbc/ws-alephamp-queue-renderer).

### Arises From

[PR (ws-alephamp-queue-renderer)](https://github.com/bbc/ws-alephamp-queue-renderer/pull/243)

### Jira Ticket
[WS2020-209](https://jira.dev.bbc.co.uk/browse/WS2020-209)

### CODE REVIEW

**Comment by wildlyinaccurate** [comment]
Looks good to me! Please could you bump the version in `package.json` and add an entry in `CHANGELOG.md`?

_Note to self: create `CONTRIBUTING.md` with these instructions :D_

**Comment by wildlyinaccurate** [comment]
I forgot to include an example PR which contains a version bump and changelog entry: https://github.com/bbc/gs-sass-tools/pull/24/files

**Comment by akabiru** [comment]
Thanks @wildlyinaccurate 🙂. Let me have a look at that.

**Comment by wildlyinaccurate** [comment]
IT'S BEAUTIFUL

**Pull request merged**
